---
default:
    - debug: true
      open: public/index-debug.html
      extras: -use-network=false -static-link-runtime-shared-libraries -default-frame-rate=60
    
library-path:
    - source/swc

source-path:
    - source/libs
    - source/classes
    - ../Potato/source/libs
    - ../Potato/source/classes
    
applications:
    - class: source/classes/simpleSite/views/Loader.as
      output: public/loader.swf
      
    - class: source/classes/simpleSite/views/Main.as
      output: public/main.swf
          
    - class: source/classes/simpleSite/views/About.as
      output: public/about.swf
    
    - class: source/classes/simpleSite/views/Contact.as
      output: public/contact.swf
      
      # exclude: source/classes/Other.as
# asdoc:
#     title: "My ActionScript project"
#     footer: "My ActionScript project footer"
#     output: docs/
#     exclude-dirs: 
#       - source/classes/com/greensock/
#       - source/classes/br/com/stimuli/
